#!/bin/sh -x

cd "`dirname $0`" &&
	if which glibtoolize >/dev/null 2>&1; then
		glibtoolize --copy --force
	else
		libtoolize --copy --force
	fi &&
	aclocal &&
	autoheader &&
	automake --add-missing &&
	autoconf &&

cd liboop && ./bootstrap
