#!/bin/sh

run() {
        printf '>>> %s\n' "$*"
        "$@"
}

run cd "`dirname $0`" &&
	run libtoolize --copy --force &&
	run aclocal &&
        run autoheader &&
	run automake --add-missing &&
	run autoconf &&

run cd liboop &&
	run libtoolize --copy --force &&
	run aclocal &&
	run automake --add-missing &&
	run autoconf
