#!/bin/sh

if [ ! -x prepare ]; then
	echo "$0: must run from root of source tree."
	exit 1
fi

if [ -d /usr/ug/share/aclocal ]; then
	ac="--acdir=/usr/ug/share/aclocal"
else
	ac=""
fi

( cd liboop && 
  aclocal $ac&& autoheader && libtoolize --automake && automake -a && autoconf )
  aclocal $ac&& autoheader && libtoolize --automake && automake -a && autoconf
