#!/bin/sh -x

[ -x "`which automake-1.7 2>/dev/null`" ] && ver="-1.7" || ver=""

if which glibtoolize >/dev/null 2>&1; then
	glibtoolize --copy --force
else
	libtoolize --copy --force
fi &&
aclocal$ver &&
automake$ver --add-missing &&
autoconf
